version: '3'

services:
  app:
    build: ./TechnicalTask_Boot
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
  postgres:
    build: ./database
    volumes:
      - postgresdb:/var/lib/postgresql
    healthcheck:
      test: 
        - CMD-SHELL
        - |
          psql -U postgres -d GameData_db -tc "SELECT 1 FROM information_schema.tables WHERE table_name = 'GameData_db';"
      interval: 1s
      timeout: 3s
      retries: 5
volumes:
  postgresdb: