services:
  app:
    build: ./TechnicalTask_Boot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5FA6Jq87_Th*9
      POSTGRES_DB_NAME: GameData_DB
    depends_on:
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    ports:
      - 8080:8080

  postgres:
    build: ./databases/Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5FA6Jq87_Th*9
      POSTGRES_DB_NAME: GameData_DB
    volumes:
      - postgresdb:/var/lib/postgresql
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 1s
      timeout: 3s
      retries: 10

  cassandra:
    build: ./databases/Cassandra
    volumes:
      - cassandradb:/var/lib/cassandra
    healthcheck:
      test:
        - CMD-SHELL
        - cqlsh -e 'SELECT release_version FROM system.local;' || exit 1
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgresdb:
  cassandradb:
