--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: user_activity_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_activity_data (
    id bigint NOT NULL,
    sync_uuid character varying,
    activity integer,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_activity_data_activity_check CHECK ((activity >= 0))
);


ALTER TABLE public.user_activity_data OWNER TO postgres;

--
-- Name: user_activity_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_activity_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_activity_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_sync_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_sync_data (
    id bigint NOT NULL,
    uuid character varying NOT NULL,
    money integer,
    country character varying,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT user_sync_data_money_check CHECK ((money >= 0))
);


ALTER TABLE public.user_sync_data OWNER TO postgres;

--
-- Name: user_sync_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_sync_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sync_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: user_activity_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_activity_data (id, sync_uuid, activity, "timestamp") FROM stdin;
\.


--
-- Data for Name: user_sync_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_sync_data (id, uuid, money, country, created_at) FROM stdin;
2	1e7	1000	RU	2023-12-04 21:24:00
3	1e9	1000	RU	2023-12-04 21:24:00
4	1e10	1000	RU	2023-12-04 21:24:00
5	1e11	1000	RU	2023-12-04 21:24:00
6	1e12	1000	RU	2023-12-04 21:24:00
1	1e6	1001	RU	2023-12-04 21:24:00
7	1e5	100	RU	2023-12-04 21:24:00
8	1e15	100	RU	2023-12-04 21:24:00
\.


--
-- Name: user_activity_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_activity_data_id_seq', 13038, true);


--
-- Name: user_sync_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_sync_data_id_seq', 8, true);


--
-- Name: user_activity_data user_activity_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_activity_data
    ADD CONSTRAINT user_activity_data_pkey PRIMARY KEY (id);


--
-- Name: user_sync_data user_sync_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_sync_data
    ADD CONSTRAINT user_sync_data_pkey PRIMARY KEY (id);


--
-- Name: user_sync_data user_sync_data_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_sync_data
    ADD CONSTRAINT user_sync_data_uuid_key UNIQUE (uuid);


--
-- Name: user_activity_data user_activity_data_sync_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_activity_data
    ADD CONSTRAINT user_activity_data_sync_uuid_fkey FOREIGN KEY (sync_uuid) REFERENCES public.user_sync_data(uuid);


--
-- PostgreSQL database dump complete
--

