apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:17
          command: ["sh", "-c", "until pg_isready -U postgres -h postgres; do sleep 3; done"]
        
        - name: wait-for-cassandra
          image: cassandra:4.0
          command: ["sh", "-c", "until cqlsh -e 'SELECT release_version FROM system.local;' cassandra; do sleep 3; done"]

      containers:
        - name: app
          image: sevabek/app:latest
          ports:
            - containerPort: 8080

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB_NAME

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            limits:
              memory: "1Gi"
              cpu: "800m"