name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      # Сборка и пуш Docker-образа для java приложения
      - name: Build and Push App Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: TechnicalTask_Boot/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/app:latest

      # Сборка и пуш Docker-образа для Cassandra
      - name: Build and Push Cassandra Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: databases/Cassandra/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/cassandra:latest

      # Сборка и пуш Docker-образа для Postgres
      - name: Build and Push Postgres Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: databases/Postgres/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/postgres:latest
