name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      # Сборка и пуш Docker-образа для java приложения
      - name: Build and Push App Image
        uses: docker/build-push-action@v3
        with:
          context: TechnicalTask_Boot
          file: TechnicalTask_Boot/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/app:latest
          cache-from: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/app:cache
          cache-to: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/app:cache,mode=max
          build-args: |
            POSTGRES_PASSWORD=${{secrets.DOCKER_POSTGRES_PASSWORD}}
            POSTGRES_DB_NAME=${{secrets.DOCKER_POSTGRES_DB_NAME}}
            POSTGRES_USER=${{secrets.DOCKER_POSTGRES_USER}}

      # Сборка и пуш Docker-образа для Cassandra
      - name: Build and Push Cassandra Image
        uses: docker/build-push-action@v3
        with:
          context: databases/Cassandra
          file: databases/Cassandra/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/cassandra:latest
          cache-from: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/cassandra:cache
          cache-to: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/cassandra:cache,mode=max

      # Сборка и пуш Docker-образа для Postgres
      - name: Build and Push Postgres Image
        uses: docker/build-push-action@v3
        with:
          context: databases/Postgres
          file: databases/Postgres/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/postgres:latest
          cache-from: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/postgres:cache
          cache-to: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/postgres:cache,mode=max
          build-args: |
            POSTGRES_PASSWORD=${{secrets.DOCKER_POSTGRES_PASSWORD}}
            POSTGRES_DB_NAME=${{secrets.DOCKER_POSTGRES_DB_NAME}}
            POSTGRES_USER=${{secrets.DOCKER_POSTGRES_USER}}
