name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{secrets.KUBE_CONFIG}}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy application
        run: |
          kubectl apply -f databases/Cassandra/stateful-set.yml -f databases/Cassandra/service.yml 
          -f databases/Postgres/stateful-set.yml -f databases/Postgres/service.yml 
          -f TechnicalTask_Boot/deployment.yml -f TechnicalTask_Boot/service.yml 
          -f sealed-secret.yml

